language: "python"
python:
   - "2.7"
   - "3.5"
sudo: false
cache: pip

install:
  - pip install flake8

before_script:
  - flake8 --version

script:
  - flake8 .
  - cd examples && flake8 .

notifications:
  email:
    recipients:
      - ppwwyyxxc@gmail.com
    on_success: never
    on_failure: change # default: always
